# Config file for automatic testing at travis-ci.org
language: python

services:
  - postgresql

matrix:
  include:
  # Linting
  - python: 3.6
    env:
      TOX_ENV: check-lint

  - python: 3.6
    env:
      TOX_ENV: py36-unit-tests
      COVERAGE_FLAG: unit

  - python: 3.6
    env:
      TOX_ENV: py36-integration-tests
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: ""
      PGHOST: 127.0.0.1
      COVERAGE_FLAG: integration

  - python: 3.6
    env:
      TOX_ENV: py36-acceptance-tests
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: ""
      PGHOST: 127.0.0.1
      COVERAGE_FLAG: ""

  - python: 3.7
    env:
      TOX_ENV: py37-unit-tests,py37-integration-tests,py37-acceptance-tests
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: ""
      PGHOST: 127.0.0.1
      COVERAGE_FLAG: ""

  - python: 3.8
    env:
      TOX_ENV: py38-unit-tests,py38-integration-tests,py38-acceptance-tests
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: ""
      PGHOST: 127.0.0.1
      COVERAGE_FLAG: ""

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - |
    if [ -n "$COVERAGE_FLAG" ];
      then bash <(curl -s https://codecov.io/bash) -c -F $COVERAGE_FLAG;
    fi
